package main

import (
	"testing"
)

func BenchmarkName(b *testing.B) {
	skiplist := Constructor()
	for i := 0; i < b.N; i++ {

		//m := map[int]int{}
		//for i := 0; i < 1000000; i++ {
		//	m[skiplist.randomLevel()]++
		//
		//}
		//m)
		skiplist.Add(16)
		skiplist.Add(5)
		skiplist.Add(14)
		skiplist.Add(13)
		skiplist.Add(0)
		skiplist.Add(3)
		skiplist.Add(12)
		skiplist.Add(9)
		skiplist.Add(12)
		skiplist.Erase(3)
		skiplist.Search(6)
		skiplist.Add(7)
		skiplist.Erase(0)
		skiplist.Erase(1)
		skiplist.Erase(10)
		skiplist.Add(5)
		skiplist.Search(12)
		skiplist.Search(7)
		skiplist.Search(16)
		skiplist.Erase(7)
		skiplist.Search(0)
		skiplist.Add(9)
		skiplist.Add(16)
		skiplist.Add(3)
		skiplist.Erase(2)
		skiplist.Search(17)
		skiplist.Add(2)
		skiplist.Search(17)
		skiplist.Erase(0)
		skiplist.Search(9)
		skiplist.Search(14)
		skiplist.Erase(1)
		skiplist.Erase(6)
		skiplist.Add(1)
		skiplist.Erase(16)
		skiplist.Search(9)
		skiplist.Erase(10)
		skiplist.Erase(9)
		skiplist.Search(2)
		skiplist.Add(3)
		skiplist.Add(16)
		skiplist.Erase(15)
		skiplist.Erase(12)
		skiplist.Erase(7)
		skiplist.Add(4)
		skiplist.Erase(3)
		skiplist.Add(2)
		skiplist.Erase(1)
		skiplist.Erase(14)
		skiplist.Add(13)
		skiplist.Add(12)
		skiplist.Add(3)
		skiplist.Search(6)
		skiplist.Search(17)
		skiplist.Add(2)
		skiplist.Erase(3)
		skiplist.Search(14)
		skiplist.Add(11)
		skiplist.Add(0)
		skiplist.Search(13)
		skiplist.Add(2)
		skiplist.Search(1)
		skiplist.Erase(10)
		skiplist.Erase(17)
		skiplist.Search(0)
		skiplist.Search(5)
		skiplist.Erase(8)
		skiplist.Search(9)
		skiplist.Add(8)
		skiplist.Erase(11)
		skiplist.Search(10)
		skiplist.Erase(11)
		skiplist.Search(10)
		skiplist.Erase(9)
		skiplist.Erase(8)
		skiplist.Search(15)
		skiplist.Search(14)
		skiplist.Add(1)
		skiplist.Add(6)
		skiplist.Add(17)
		skiplist.Add(16)
		skiplist.Search(13)
		skiplist.Search(4)
		skiplist.Search(5)
		skiplist.Search(4)
		skiplist.Search(17)
		skiplist.Search(16)
		skiplist.Search(7)
		skiplist.Search(14)
		skiplist.Search(1)
	}
}
